name: Update Report
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron: "0 */6 * * *" 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        architecture: 'x64'
    - name: Install numpy
      run: pip install numpy
    - name: Install library and other requirements
      run: |
        pip install jupyter nbconvert
        pip install -r requirements.txt 
    - name: Run Notebooks
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        wget -q https://nvd.handsonhacking.org/nvd.jsonl 
        jupyter nbconvert --ExecutePreprocessor.timeout=-1 --to notebook --inplace --execute Kalman_2025.ipynb
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
          default_author: github_actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}